algoritmo "Para - Passo"

var
   i, w, start, end: inteiro

inicio

      Escreval("Começo")
      leia(start)
      Escreval("Fim")
      leia(end)
      Escreval("Decremento")
      leia(w)
      
      // com a tecnica do passo eu posso pegar os numeros pares, impares, multiplos
      // e ainda fazer uma para reverso
      para i de start ate end passo w faca
           Escreval(i)
      fimpara

fimalgoritmo
